name: "Test"

on: push

jobs:
  jest:
    name: "Jest"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "npm"
      - run: npm install
      - run: npm run test

  test:
    name: "Test"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
